'use strict';

const { env } = process;

module.exports = {
  BLOB_ACCOUNT_NAME: env.BLOB_ACCOUNT_NAME,
  BLOB_SECRET: env.BLOB_SECRET,
  CONTAINER_PASSWORD_METADATA_NAME: env.CONTAINER_PASSWORD_METADATA_NAME,
  HOST: env.FTP_HOST,
  PORT: env.FTP_PORT,
  PASSVPORTMIN: env.FTP_PASSVPORTMIN,
  PASSVPORTMAX: env.FTP_PASSVPORTMAX,
  CERT_KEY_PATH: env.CERT_KEY_PATH,
  CERT_PATH: env.CERT_PATH,
  CERT_FULL_PATH: env.CERT_FULL_PATH,
  USERNAME_WEB_REPLACE: env.USERNAME_WEB_REPLACE
};
